### ISSUE TITLE
split_at/4

### ISSUE THREAD

**Issue by eazar001** [mndrix/list_util#13]
A predicate like this may be a useful addition. Is this valid?
```
%% split_at(+N, +Xs, -Take, -Rest)
%
% True if Take is a list containing the first N elements of Xs and Rest contains 
% the remaining elements.

split_at(0, Xs, [], Xs) :- !.
split_at(N, [X|Xs], [X|Ys], Zs) :-
  N > 0,
  succ(N0, N),
  split_at(N0, Xs, Ys, Zs).
```

**Comment by mndrix** [comment]
This seems like a helpful addition.  Can you send a pull request with an implementation and test cases?  If not, I can try to find time to add this when I get back home next week.

**Comment by eazar001** [comment]
Sure, I'll send you a pull request when I get the chance.

**Comment by triska** [comment]
I have two suggestions about this:

1) consider using CLP(FD) constraints to make such relations more general.

2) consider making the names more declarative, so that it is easy to remember which argument stands for what.

For example:

    :- use_module(library(clpfd)).

    list_at_split(Ls, N, As, Bs) :-
            zcompare(C, 0, N),
            list_split_at_(C, Ls, N, As, Bs).

    list_split_at_(=, Ls, _, [], Ls).
    list_split_at_(<, [L|Ls], N0, [L|As], Bs) :-
            N1 #= N0 - 1,
            zcompare(C, 0, N1),
            list_split_at_(C, Ls, N1, As, Bs).

Now, I can use this in the most general way:

    ?- list_at_split(Ls, N, As, Bs).
    Ls = Bs,
    N = 0,
    As = [] ;
    Ls = [_G56|Bs],
    N = 1,
    As = [_G56]  ;
    etc.

Or, I can ask for more concrete cases:

   ?- list_at_split([a,b,c], 2, As, Bs).
   As = [a, b],
   Bs = [c].

etc. I'm not saying this name is already optimal: With some thought, you will likely find a better one.

Still, I hope these suggestions are useful for you.
